<?php

/**
 * @file
 * Contains mvf.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mvf_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mvf module.
    case 'help.page.mvf':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Define a field with an amount and a unit of measurement.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mvf_theme() {
  $theme = [];

  return $theme;
}
