<?php

/**
 * @file
 * Module that allows to specify output units for MVF fields on per user basis.
 */

/**
 * Implements hook_menu().
 */
function mvf_per_user_menu() {
  $items = array();

  // TODO: maybe it'd be cool to have some general overview table where admin
  // can see current statuses of all MVF fields, whether per user output units
  // are enabled for them.

  $items['mvf-per-user/%mvf_per_user_field'] = array(
    'title' => 'Output Unit for MVF fields',
    'title callback' => 'mvf_per_user_config_form_title',
    'title arguments' => array(1),
    'description' => 'Define whether users can control output units for a MVF field.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mvf_per_user_config_form', 1),
    'access arguments' => array('administer mvf output per user'),
    'file' => 'mvf_per_user.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function mvf_per_user_permission() {
  return array(
    'administer mvf output per user' => array(
      'title' => t('Administer MVF output per user'),
      'description' => t('Administer output units for MVF fields on per user basis.'),
    ),
  );
}

/**
 * Implements hook_mvf_unit_suggester_info().
 */
function mvf_per_user_mvf_unit_suggester_info() {
  $output = array(
    'MVFPerUserUnitSuggesterUser',
  );
  return $output;
}

/**
 * Generate name for a unit field from MVF field, which it represents.
 *
 * @param array $mvf_field
 *   MVF field array definition, name of unit field for this MVF field will be
 *   returned
 *
 * @return string
 *   Name for a unit field of a provided MVF field
 *
 * @throws FieldException
 */
function mvf_per_user_unit_field_name($mvf_field) {
  // There is a limit of 32 chars for a field name in Field API.
  $max_length = 32;
  $prefix = 'mvfu_';
  $name = $prefix . $mvf_field['field_name'];
  if (drupal_strlen($name) > $max_length) {
    throw new FieldException(t('Machine name of your MVF field %field_name is too long. MVF per User cannot create a corresponding unit field, because its machine name length would exceed allowed by Field API max length of 32 chars. Please, use a MVF field with machine name shorter than %max_length.', array(
      '%field_name' => $mvf_field['field_name'],
      '%max_length' => $max_length - drupal_strlen($prefix),
    )));
  }
  return $name;
}

/**
 * Menu load function.
 *
 * Load a MVF field by its machine name.
 *
 * @param string $field_name
 *   Machine name of a MVF field to load
 *
 * @return array|bool
 *   Field definition array or FALSE if such MVF field does not exist
 */
function mvf_per_user_field_load($field_name) {
  $field = field_info_field($field_name);
  if (in_array($field['type'], mvf_field_types())) {
    return $field;
  }
  return FALSE;
}

/**
 * Load function for unit field of a MVF field.
 *
 * In the unit field users can store desired output unit for a corresponding MVF
 * field.
 *
 * @param string $field_name
 *   Machine name of a MVF field, whose unit field should be loaded
 *
 * @return array|bool
 *   Fully loaded field definition array of unit field or FALSE if such unit
 *   field does not exist
 */
function mvf_per_user_unit_field_load($field_name) {
  $field = mvf_per_user_field_load($field_name);
  try {
    $unit_field_name = mvf_per_user_unit_field_name($field);
  }
  catch (FieldException $e) {
    return FALSE;
  }
  $unit_field = field_info_field($unit_field_name);
  return is_array($unit_field) ? $unit_field : FALSE;
}

/**
 * Menu title callback for path 'mvf-per-user/%mvf_per_user_field'.
 *
 * @param array $mvf_field
 *   Fully loaded MVF field, for which per user output unit status could be
 *   changed
 *
 * @return string
 *   Title for the path 'mvf-per-user/%mvf_per_user_field'
 */
function mvf_per_user_config_form_title($mvf_field) {
  return t('Output Unit on per User Basis for "!field_name" field', array(
    '!field_name' => $mvf_field['field_name'],
  ));
}
